const languageList = [
  `English (English)`,
  `Afar (Afaraf)`,
  `Abkhaz (аҧсуа бызшәа, аҧсшәа)`,
  `Avestan (avesta)`,
  `Afrikaans (Afrikaans)`,
  `Akan (Akan)`,
  `Amharic (አማርኛ)`,
  `Aragonese (aragonés)`,
  `Arabic (العربية)`,
  `Assamese (অসমীয়া)`,
  `Avaric (авар мацӀ, магӀарул мацӀ)`,
  `Aymara (aymar aru)`,
  `Azerbaijani (azərbaycan dili)`,
  `South Azerbaijani (تورکجه‎)`,
  `Bashkir (башҡорт теле)`,
  `Belarusian (беларуская мова)`,
  `Bulgarian (български език)`,
  `Bihari (भोजपुरी)`,
  `Bislama (Bislama)`,
  `Bambara (bamanankan)`,
  `Bengali; Bangla (বাংলা)`,
  `Tibetan Standard, Tibetan, Central (བོད་ཡིག)`,
  `Breton (brezhoneg)`,
  `Bosnian (bosanski jezik)`,
  `Catalan; Valencian (català, valencià)`,
  `Chechen (нохчийн мотт)`,
  `Chamorro (Chamoru)`,
  `Corsican (corsu, lingua corsa)`,
  `Cree (ᓀᐦᐃᔭᐍᐏᐣ)`,
  `Czech (čeština, český jazyk)`,
  `Old Church Slavonic, Church Slavonic, Old Bulgarian (ѩзыкъ словѣньскъ)`,
  `Chuvash (чӑваш чӗлхи)`,
  `Welsh (Cymraeg)`,
  `Danish (dansk)`,
  `German (Deutsch)`,
  `Divehi; Dhivehi; Maldivian; (ދިވެހި)`,
  `Dzongkha (རྫོང་ཁ)`,
  `Ewe (Eʋegbe)`,
  `Greek, Modern (ελληνικά)`,
  `Esperanto (Esperanto)`,
  `Spanish; Castilian (español, castellano)`,
  `Estonian (eesti, eesti keel)`,
  `Basque (euskara, euskera)`,
  `Persian (Farsi) (فارسی)`,
  `Fula; Fulah; Pulaar; Pular (Fulfulde, Pulaar, Pular)`,
  `Finnish (suomi, suomen kieli)`,
  `Fijian (vosa Vakaviti)`,
  `Faroese (føroyskt)`,
  `French (français, langue française)`,
  `Western Frisian (Frysk)`,
  `Irish (Gaeilge)`,
  `Scottish Gaelic; Gaelic (Gàidhlig)`,
  `Galician (galego)`,
  `Guaraní (Avañe'ẽ)`,
  `Gujarati (ગુજરાતી)`,
  `Manx (Gaelg, Gailck)`,
  `Hausa (Hausa, هَوُسَ)`,
  `Hebrew (modern) (עברית)`,
  `Hindi (हिन्दी, हिंदी)`,
  `Hiri Motu (Hiri Motu)`,
  `Croatian (hrvatski jezik)`,
  `Haitian; Haitian Creole (Kreyòl ayisyen)`,
  `Hungarian (magyar)`,
  `Armenian (Հայերեն)`,
  `Herero (Otjiherero)`,
  `Interlingua (Interlingua)`,
  `Indonesian (Bahasa Indonesia)`,
  `Interlingue (Originally called Occidental; then Interlingue after WWII)`,
  `Igbo (Asụsụ Igbo)`,
  `Nuosu (ꆈꌠ꒿ Nuosuhxop)`,
  `Inupiaq (Iñupiaq, Iñupiatun)`,
  `Ido (Ido)`,
  `Icelandic (Íslenska)`,
  `Italian (italiano)`,
  `Inuktitut (ᐃᓄᒃᑎᑐᑦ)`,
  `Japanese (日本語 (にほんご))`,
  `Javanese (basa Jawa)`,
  `Georgian (ქართული)`,
  `Kongo (KiKongo)`,
  `Kikuyu, Gikuyu (Gĩkũyũ)`,
  `Kwanyama, Kuanyama (Kuanyama)`,
  `Kazakh (қазақ тілі)`,
  `Kalaallisut, Greenlandic (kalaallisut, kalaallit oqaasii)`,
  `Khmer (ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ)`,
  `Kannada (ಕನ್ನಡ)`,
  `Korean (한국어 (韓國語), 조선어 (朝鮮語))`,
  `Kanuri (Kanuri)`,
  `Kashmiri (कश्मीरी, كشميري‎)`,
  `Kurdish (Kurdî, كوردی‎)`,
  `Komi (коми кыв)`,
  `Cornish (Kernewek)`,
  `Kyrgyz (Кыргызча, Кыргыз тили)`,
  `Latin (latine, lingua latina)`,
  `Luxembourgish, Letzeburgesch (Lëtzebuergesch)`,
  `Ganda (Luganda)`,
  `Limburgish, Limburgan, Limburger (Limburgs)`,
  `Lingala (Lingála)`,
  `Lao (ພາສາລາວ)`,
  `Lithuanian (lietuvių kalba)`,
  `Luba-Katanga (Tshiluba)`,
  `Latvian (latviešu valoda)`,
  `Malagasy (fiteny malagasy)`,
  `Marshallese (Kajin M̧ajeļ)`,
  `Māori (te reo Māori)`,
  `Macedonian (македонски јазик)`,
  `Malayalam (മലയാളം)`,
  `Mongolian (монгол)`,
  `Marathi (Marāṭhī) (मराठी)`,
  `Malay (bahasa Melayu, بهاس ملايو‎)`,
  `Maltese (Malti)`,
  `Burmese (ဗမာစာ)`,
  `Nauru (Ekakairũ Naoero)`,
  `Norwegian Bokmål (Norsk bokmål)`,
  `North Ndebele (isiNdebele)`,
  `Nepali (नेपाली)`,
  `Ndonga (Owambo)`,
  `Dutch (Nederlands, Vlaams)`,
  `Norwegian Nynorsk (Norsk nynorsk)`,
  `Norwegian (Norsk)`,
  `South Ndebele (isiNdebele)`,
  `Navajo, Navaho (Diné bizaad, Dinékʼehǰí)`,
  `Chichewa; Chewa; Nyanja (chiCheŵa, chinyanja)`,
  `Occitan (occitan, lenga d'òc)`,
  `Ojibwe, Ojibwa (ᐊᓂᔑᓈᐯᒧᐎᓐ)`,
  `Oromo (Afaan Oromoo)`,
  `Oriya (ଓଡ଼ିଆ)`,
  `Ossetian, Ossetic (ирон æвзаг)`,
  `Panjabi, Punjabi (ਪੰਜਾਬੀ, پنجابی‎)`,
  `Pāli (पाऴि)`,
  `Polish (język polski, polszczyzna)`,
  `Pashto, Pushto (پښتو)`,
  `Portuguese (português)`,
  `Quechua (Runa Simi, Kichwa)`,
  `Romansh (rumantsch grischun)`,
  `Kirundi (Ikirundi)`,
  `Romanian (limba română)`,
  `Russian (русский язык)`,
  `Kinyarwanda (Ikinyarwanda)`,
  `Sanskrit (Saṁskṛta) (संस्कृतम्)`,
  `Sardinian (sardu)`,
  `Sindhi (सिन्धी, سنڌي، سندھی‎)`,
  `Northern Sami (Davvisámegiella)`,
  `Sango (yângâ tî sängö)`,
  `Sinhala, Sinhalese (සිංහල)`,
  `Slovak (slovenčina, slovenský jazyk)`,
  `Slovene (slovenski jezik, slovenščina)`,
  `Samoan (gagana fa'a Samoa)`,
  `Shona (chiShona)`,
  `Somali (Soomaaliga, af Soomaali)`,
  `Albanian (gjuha shqipe)`,
  `Serbian (српски језик)`,
  `Swati (SiSwati)`,
  `Southern Sotho (Sesotho)`,
  `Sundanese (Basa Sunda)`,
  `Swedish (Svenska)`,
  `Swahili (Kiswahili)`,
  `Tamil (தமிழ்)`,
  `Telugu (తెలుగు)`,
  `Tajik (тоҷикӣ, toğikī, تاجیکی‎)`,
  `Thai (ไทย)`,
  `Tigrinya (ትግርኛ)`,
  `Turkmen (Türkmen, Түркмен)`,
  `Tagalog (Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔)`,
  `Tswana (Setswana)`,
  `Tonga (Tonga Islands) (faka Tonga)`,
  `Turkish (Türkçe)`,
  `Tsonga (Xitsonga)`,
  `Tatar (татар теле, tatar tele)`,
  `Twi (Twi)`,
  `Tahitian (Reo Tahiti)`,
  `Uyghur, Uighur (Uyƣurqə, ئۇيغۇرچە‎)`,
  `Ukrainian (українська мова)`,
  `Urdu (اردو)`,
  `Uzbek (O‘zbek, Ўзбек, أۇزبېك‎)`,
  `Venda (Tshivenḓa)`,
  `Vietnamese (Tiếng Việt)`,
  `Volapük (Volapük)`,
  `Walloon (walon)`,
  `Wolof (Wollof)`,
  `Xhosa (isiXhosa)`,
  `Yiddish (ייִדיש)`,
  `Yoruba (Yorùbá)`,
  `Zhuang, Chuang (Saɯ cueŋƅ, Saw cuengh)`,
  `Chinese (中文 (Zhōngwén), 汉语, 漢語)`,
  `Zulu (isiZulu)`,
];

export default languageList;
